opengeos/segment-geospatial

.gitignore
README.md
docs/examples/automatic_mask_generator.ipynb
docs/examples/satellite-predictor.ipynb
docs/examples/satellite.ipynb
docs/index.md
mkdocs.yml
samgeo/common.py
samgeo/samgeo.py

New features for v0.4.0

---

docs/examples/satellite-predictor.ipynb
docs/examples/satellite.ipynb
samgeo/common.py
samgeo/samgeo.py

This PR fixes the batch processing bug reported in #28

Fix the batch processing bug

---

README.md
docs/index.md
samgeo/common.py
samgeo/samgeo.py

```python
sam.show_map()
```
https://github.com/opengeos/segment-geospatial/assets/5016453/64ebd3c4-af66-426b-baf0-fb53b439a92f

Add interactive GUI for creating foreground and background markers

---

samgeo/common.py

This PR provides a temporary workaround for the displaying markers with AwesomeIcon on Colab. It will use CircleMarker instead.

Fix Colab AwesomeIcon bug

---

.github/workflows/docker-image.yml
.github/workflows/docker-publish.yml
Dockerfile
docs/installation.md

This PR adds a Dockerfile and GitHub Actions for building docker image and publishing it on Docker Hub and GitHub Registry

Add Dockerfile

---

samgeo/samgeo.py

The PR makes the `show_masks` method compatible with the batch mode. The `show_anns` does not support batch mode yet.

Add show_masks for batch mode

---

docs/installation.md

Updated docker instruction

---

README.md
docs/examples/arcgis.ipynb
docs/index.md
mkdocs.yml

This PR adds an ArcGIS notebook example for using segment-geospatial

Add ArcGIS notebook example

---

docs/examples/arcgis.ipynb
docs/examples/automatic_mask_generator.ipynb

Small changes to prevent hangups.
leafmap.arc_zoom_to_bounds() is not yet part of the release.

notebook tweaks

---

docs/examples/arcgis.ipynb
docs/examples/input_prompts.ipynb
mkdocs.yml
samgeo/samgeo.py

The PR updates the ArcGIS notebook and remove basemap download section to avoid legal issues.

Update ArcGIS notebook

---

README.md
docs/examples/arcgis.ipynb
docs/examples/automatic_mask_generator.ipynb
docs/examples/input_prompts.ipynb
docs/examples/satellite.ipynb
docs/examples/text_prompts.ipynb
docs/index.md
mkdocs.yml
samgeo/common.py
samgeo/samgeo.py
samgeo/text_sam.py

This PR revises the `text_sam` module and makes it easier to use text prompts for image segmentation.

Add support for using text prompts with SAM

---

docs/examples/text_prompts.ipynb
samgeo/samgeo.py
samgeo/text_sam.py

Improve text prompt notebook

---

docs/examples/text_prompts.ipynb
samgeo/common.py
samgeo/samgeo.py
samgeo/text_sam.py
tests/test_samgeo.py

Add interactive GUI for image segmentation with text prompts

---

samgeo/common.py

Add rectangularize option for vector output

---

docs/examples/swimming_pools.ipynb
mkdocs.yml
samgeo/common.py

Mapping swimming pools with text prompts.

Add swimming pools example

---

samgeo/common.py

The simplified code may be slightly more readable and concise.
The performance difference between the two approaches is likely to be minimal.

sorted function instead of if statements

---

samgeo/common.py

This PR fixes the file deletion error on Winows #121

Fix file deletion error on Windows

---

samgeo/common.py

This PR fixes the issue reported in #125

Improve exception handling for LangSAM GUI

---

samgeo/samgeo.py

This PR fixes the bug reported in #124

Fix image source bug for show_anns

---

docs/examples/text_prompts_batch.ipynb
samgeo/samgeo.py
samgeo/text_sam.py

Fix model download bug

---

samgeo/requirements.txt
samgeo/samgeo.py

Fix save_masks bug without source image

---

docs/examples/arcgis.ipynb
docs/examples/automatic_mask_generator.ipynb
docs/examples/box_prompts.ipynb
docs/examples/input_prompts.ipynb
docs/hq_sam.md
mkdocs.yml
requirements.txt
requirements_dev.txt
samgeo/common.py
samgeo/hq_sam.py
samgeo/samgeo.py

https://github.com/SysCV/sam-hq

Add support for HQ-SAM

---

README.md
docs/contributing.md

Fix #166
Reference: https://github.com/openjournals/joss-reviews/issues/5663

Improve contributing guidelines

---

README.md
docs/installation.md

Add installation instructions to README

---

samgeo/common.py

Fix basemap issue

---

samgeo/text_sam.py

So when we use LangSAM() to predict geographic elements，we can custom checkpoint of SAM.

Add checkpoint to textsam.LangSAM()

---

docs/workshops/purdue.ipynb
mkdocs.yml

Add workshop notebook for Purdue GIS Day.

Add workshop notebook

---

requirements.txt

Add xarray to requirements.txt

---

.gitignore
docs/examples/sam2_predictor.ipynb
docs/examples/sam2_video.ipynb
mkdocs.yml

This PR adds three SAM 2 notebook examples
- automatic
- predictor
- video

Add SAM 2 notebook examples

---

samgeo/samgeo.py

Fix save masks bug

---

samgeo/common.py

Fix vector_to_geojson bug

---

docs/workshops/IPPN_2024.ipynb
samgeo/common.py
samgeo/samgeo2.py

Add support for intensity image (such as DEM, DSM, CHM) when calcualting zonal stats.

Add zonal stats to region groups

---

docs/examples/sam2_text_prompts.ipynb
mkdocs.yml
samgeo/text_sam.py

Add text-prompt support for SamGeo2

---

samgeo/common.py

Fix env var error

---

docs/examples/sam2_point_prompts.ipynb
mkdocs.yml
samgeo/common.py
samgeo/samgeo.py
samgeo/samgeo2.py

Add predict_by_points method

---

docs/workshops/AIforGood_2025.ipynb
docs/workshops/jupytext.toml
mkdocs.yml

https://aiforgood.itu.int/event/mastering-remote-sensing-image-segmentation-with-ai-a-hands-on-workshop-with-the-segment-anything-model/

Add AI for Good workshop notebook

---

samgeo/common.py

Add support for simplifying polygons

---

samgeo/common.py
samgeo/samgeo.py
samgeo/samgeo2.py

Add crs and transform for array input
