docs/examples/satellite-predictor.ipynb
samgeo/common.py
samgeo/samgeo.py

This PR introduces a new class, SamGeoPredictor.
The new class inherits from the segment-anything [Predictor](https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/predictor.py) class, and introduces a new optional argument, `geo_box` which can be used to spatially limit the segmentation area. There are also new methods for `masks_to_geotiff` (outputting georeferenced images after the predictor is initialized) and `geotiff_to_geojson` (vectorizing raster segmentation). Otherwise, the new class should behave the same as the parent Predictor class.
This PR can be used as a starting point for #5 .

Add SamGeoPredictor class, associated helper functions, and notebook

---

samgeo/common.py
samgeo/samgeo.py

Although SAM accepts multiple input points for segmenting objects. However, all points are treated as they belong to the same object, which results in bad segmentation results and over estimation. This PR adds a `predict_batch` function that will loops through each input point/bounding box to segment each object individually and merge the results as a single raster/vector.

Add support for custom projection bbox

---

docs/examples/satellite.ipynb
docs/usage.md

Usage documentation has a mask output with `.tiff` which doesn't fit the code logic in `common.array_to_image()` for tiffs.
this would ultimately break georeferencing, among other things.
Please accept this PR so other copy-pasters like me won't need to debug the internals ;)
thanks for the lib!
nas

Use proper extension in the usage documentation

---

Dockerfile

Necessary for leafmap.Map.add_raster to work in notebooks running via Docker Desktop (Windows) https://jupyter-server-proxy.readthedocs.io/en/latest/install.html

Install and enable jupyter-server-proxy

---

requirements.txt
samgeo/text_sam.py

This PR adds huggingface_hub and removes onnx and onnxruntime from requirements.txt.
I am adding supervision and groundingdino to conda-forge (https://github.com/conda-forge/staged-recipes/pull/22907). GroudingDINO can be added to requirements.txt once they become available on conda-forge.

Add huggingface_hub and remove onnx

---

samgeo/text_sam.py

Makes sure the output filename is the same as the input. Possible fix for #85.

Use the force_filename parameter with hf_hub_download()

---

samgeo/common.py

I noticed a small typo in the variable name "rigth_x_bound".

misspelled variable - fixed spelling rigth -> right

---

samgeo/common.py

It seems that the 'image' argument is not necessary for the current implementation of the 'show_box' function.

removed 'image' argument - was not being used in the show_box function

---

samgeo/common.py

It seems that the 'flags' and 'param' arguments are not necessary for the current implementation of the 'get_mouse_coordinates' function.

removed 'flags' and 'param' arguments - they were not being used

---

README.md
docs/examples/text_prompts_batch.ipynb
docs/index.md
mkdocs.yml
samgeo/common.py
samgeo/text_sam.py

This PR adds support for batch segmentation with text prompts. This can be useful when an image is too large for the GPU. Splitting the image into smaller tiles and segmenting each tile and merge the results as a single GeoTIFF.

Add support for batch segmentation

---

samgeo/text_sam.py

When the input is a PIL image, the text_sam/predict is unable to use the numpy image for mask generation
because no such thing exists. 
Fix: Probably it would be nicer to use dimensions from the PIL image, 
but the bugfix is easier to understand in this format.

Fix mask bug in text_sam/predict when the input is PIL image

---

docs/installation.md

Finally, groundingdino is avalable on conda-forge now. 
```bash
mamba install -c conda-forge groundingdino-py
```
https://anaconda.org/conda-forge/groundingdino-py

Update groundingdino installation

---

requirements_dev.txt

Remove `segment-anything-hq` from the optional dependency list as it has been added to the required dependency list.

Update optional dependencies

---

samgeo/hq_sam.py
samgeo/samgeo.py

This PR added missing conversions from BGR to RGB after reading an input image using OpenCV.
I opened an issue #170 to report this bug.

[FIX] Added missing conversions from BGR to RGB

---

samgeo/common.py
samgeo/samgeo.py

Ignore points outside image boundary

---

docs/examples/maxar_open_data.ipynb
requirements.txt
samgeo/common.py
samgeo/fast_sam.py

This PR changes the checkpoints download URLs from Google Drive to GitHub. Now all the samgeo models are available on GitHub at https://github.com/opengeos/datasets/releases/tag/models.

Change checkpoints download URLs

---

samgeo/common.py
samgeo/samgeo.py

Hi @giswqs, just suggesting two things which I found sped up processing time significantly on larger rasters.  
- allow the sample window size to be set from samgeo.generate. Fewer, larger windows take less time as long as you have the memory.
- Skip any sample windows which are 100% nodata, with the option to set lower thresholds.

Two speedups

---

README.md

The README has this extra code block start that makes this section render improperly.
Currently looks like:
With the changes here:

Remove stray code block start in `README`

---

samgeo/common.py

I got a `zero positional argument error` from gdal.Warp when called from common.merge_rasters.
In looking at the code, I changed to using gdal.WarpOptions which resolved the error.

Use gdal.WarpOptions when merging rasters

---

samgeo/text_sam.py

Some functions within segment-geospatial don't rely on a valid CRS, but others like `save_boxes()` expects a valid CRS to be set before reprojecting to a `dst_crs`.  The source crs should be set by reading metadata from input image, but if not available, it would be helpful to see a warning while reading of the input image so you are not as surprised when `save_boxes` throws an error.

Added UserWarning when CRS of input image is None

---

samgeo/text_sam.py

Hey @giswqs...I was interested in being able to have finer-grain control over the filtering of detections, especially during `batch_predict`.
Just an idea, but what about adding a callable `detection_filter` arg to `predict()`? 
...which expects a function like:
```python
def max_25_detections_filter_func(box, mask, logit, phrase, i) -> bool:
return i < 25
```
To then be passed in kwargs down the line...
```python 
sam.batch_predict(..., detection_filter=max_25_detections_filter_func) 
```
I've implemented the following above, and seems to work well, but would appreciate hearing other people's perspectives on the API for something like this.

Add `detection_filter` to `predict()` method to allow for user-defined logic

---

samgeo/text_sam.py

Hypothetically one could create a detection filter
like:
```python
class DetectionFilter():
def __init__(self, data):
self.data = data
def __call__(self, box, mask, logit, phrase, i):
return phrase == self.data
sam.predict(..., detection_filter=DetectionFilter(data='mystring'))
```

Fixes a small bug with `detection_filter` so that instance methods work as expected

---

.github/workflows/ubuntu.yml
requirements.txt

sam2 is now available on conda-forge. This PR adds sam2 as a dependency. Support for sam2 will be added later. 
https://anaconda.org/conda-forge/sam2

Add sam2 as a dependency

---

README.md
docs/index.md
docs/samgeo2.md
mkdocs.yml
requirements.txt
samgeo/__init__.py
samgeo/common.py
samgeo/samgeo2.py

This PR adds support for Meta's Segment Anything Model 2 (SAM 2).
https://github.com/facebookresearch/segment-anything-2
https://github.com/IDEA-Research/Grounded-SAM-2?tab=readme-ov-file#grounded-sam-2-video-object-tracking-demo
Work in progress

Add support for SAM 2

---

samgeo/samgeo.py
samgeo/samgeo2.py

When saving the masks with unique ids, the large background objects overwrite the small objects inside, which is incorrect. This PR fixes it. 
Annotations:
before the fix:
after the fix:

Fix save masks bug

---

samgeo/samgeo.py
samgeo/samgeo2.py

This PR adds `min_size` and `max_size` params for removing small and large objects. 
```python
sam2.generate(image, output="masks.tif", unique=True)
```
```python
sam2.generate(image, output="masks.tif", min_size=1000, max_size=10000, unique=True)
```

Add support for filtering objets by size

---

requirements.txt
samgeo/common.py
samgeo/samgeo2.py

This PR adds the `region_groups` function for filtering objects by size, filing holes, and calculating geometric properties of each object.

Add support for calculating geometric properties of objects

---

docs/examples/sam2_box_prompts.ipynb
mkdocs.yml
samgeo/common.py
samgeo/samgeo2.py

Add support for box prompts for SamGeo2

---

Dockerfile

This PR fixes two dependency issues with the current Dockerfile (which is based on Ubuntu 22.04.3 LTS)
- adds `libgl1` to fix `ImportError: libGL.so.1: cannot open shared object file`
- adds `backports.tarfile` to fix  `Exception: cannot import name 'tarfile' from 'backports'`

Dockerfile update to fix dependency issues

---

samgeo/text_sam.py

I'm adding a GRASS addon [i.sam2](https://github.com/OSGeo/grass-addons/pull/1244) and found this bug during implementation. The issue occurs when you pass a *PIL Image* as input to `LangSAM.predict`. During this case the image source is not set. However, this causes an issue when `LangSam.predict_sam` is called throwing a value error in `SamGeo2.set_image`.

text_sam: Fixed issue when passing PIL Image as input to SamGeo2

---

Dockerfile

sam2 1.0 requires GPU, which requires a lot of space to build, exceeding the space limit of GitHub Actions. 
https://anaconda.org/conda-forge/sam2/files

Pin sam2 version in Dockerfile

---

samgeo/fast_sam.py

Fixes https://github.com/opengeos/segment-geospatial/issues/325

undefined attribute in fast sam, fixed by setting the image variable

---

requirements_docs.txt
samgeo/common.py

Bug Description
On colab, When clicking on the background radio button in the SAM map GUI, an arbitrary point is added to the map at the location of the click. This happens because the map's click event handler is being triggered when interacting with UI elements.
Steps to Reproduce
Initialize the SAM map GUI
Click on the "Background" radio button
Observe that a point is added to the map at the location of the click
Expected Behavior
Clicking on the radio button should only change the selection mode without adding a point to the map.
Proposed Solution
The issue is in the handle_map_interaction function in common.py. The map's click event handler needs to be modified to ignore clicks that occur on UI elements.
I Tested on colab and working as expected

Fix map interaction bug

---

README.md
docs/examples/automatic_mask_generator.ipynb
docs/examples/automatic_mask_generator_hq.ipynb
docs/examples/box_prompts.ipynb
docs/examples/fast_sam.ipynb
docs/examples/input_prompts.ipynb
docs/examples/input_prompts_hq.ipynb
docs/examples/maxar_open_data.ipynb
docs/examples/sam2_box_prompts.ipynb
docs/examples/sam2_point_prompts.ipynb
docs/examples/satellite-predictor.ipynb
docs/examples/satellite.ipynb
docs/examples/text_prompts.ipynb
docs/examples/text_prompts_batch.ipynb
docs/examples/text_swimming_pools.ipynb
pyproject.toml
requirements.txt
samgeo/__init__.py
samgeo/common.py
samgeo/fast_sam.py
samgeo/fer.py
samgeo/hq_sam.py
samgeo/samgeo.py
samgeo/samgeo2.py
samgeo/text_sam.py
tests/test_common.py
tests/test_samgeo.py

Added optional imports, so that the package can be imported in multiple ways without the need to pull all dependencies.
FastSAM is not working because the versions pinned on the package are too old and are not properly loading the model after `torch>2.6.0`, I will take a look at that package. I believe we should pin all required versions in this package as well to prevent these kind of errors in the future.

feat: Optional imports
